export type RootStackParamList = {
  Splash: undefined;
  Onboarding: undefined;
  UserHomeScreen: undefined;
  DietitianHomeScreen: undefined;
  UserProfileScreen: undefined;
  Login: undefined;
  ForgotPassword: undefined;
  Register: undefined;
  DietitianRegister: undefined;
  DietitianProfileScreen: undefined;
  ReviewScreen: undefined;
  DietPlanScreen:undefined;
  ProgressScreen: undefined;
  FindDietitianScreen: { query: string };
  HealthMetricsScreen:undefined;
  SettingsScreen:undefined;
  ChatListScreen: undefined;
  ChatScreen: { roomId: number };
  ResetPasswordConfirm: {
    uidb64: string;
    token: string;
  };
  AppointmentScreen: undefined;
  CreateAppointmentScreen: undefined;
  DietitianChatListScreen: undefined;
  DietitianChatScreen: { roomId: number };
  MatchScreen: undefined;
  DietitianDietPlanScreen: undefined;
  DietitianProgressScreen: undefined;
  RecipesScreen: undefined;
  WorkoutsScreen: undefined;
  DietitianReviewScreen: undefined;
};
